Repository hash-define-organization/hashdefine-onlineIDE, pull requests merged in 2022-03, with the labels that each got.

#12 UserModel
  backend/.gitignore
  backend/models/User.js
  backend/package-lock.json
  backend/package.json
Labels: level-2, GSSoC'22

#17 Shows error on code failure
  src/Components/Main/Main.js
  src/Components/Terminal/Terminal.js
Labels: GSSoC'22

#20 Update README.md
  README.md
Labels: good first issue, level-1, GSSoC'22

#22 Added responsiveness to the IDE
  src/Components/CodeEditor/CodeEditor.scss
  src/Components/Header/Header.js
  src/Components/Header/Header.scss
  src/Components/Terminal/Terminal.scss
  src/index.scss
Labels: level-2, GSSoC'22

#25 Title and logo of the website changed
  public/index.html
  public/logo.png
Labels: level-1, GSSoC'22
